language: node_js
sudo: false

node_js:
  - 4
  - node

notifications:
  email: false

after_script:
  - sed -i 's/masters.js/ffasub.js/' package.json
  - npm test
  - sed -i 's/ffasub.js/masters.js/' package.json
  - npm install coveralls
  - npm run coverage | coveralls
